# Generated by Django 3.0.5 on 2020-06-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('user_account', '0005_auto_20200610_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile2',
        ),
    ]
