# Generated by Django 3.0.5 on 2020-05-31 07:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyUserAccount',
            new_name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
