# Generated by Django 3.0.5 on 2020-06-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0002_auto_20200531_0756'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
