# Generated by Django 3.0.5 on 2020-06-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('core', '0006_userprofile3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile2',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='userprofile3',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserProfile2',
        ),
        migrations.DeleteModel(
            name='UserProfile3',
        ),
    ]
