# Generated by Django 3.0.5 on 2020-05-20 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_course_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='course',
        ),
    ]
