# Generated by Django 3.0.5 on 2020-05-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20200520_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='classroom',
            field=models.ManyToManyField(blank=True, null=True, related_name='groups', to='group.Classroom'),
        ),
    ]
