# Generated by Django 3.0.5 on 2020-05-24 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20200520_1717'),
        ('group', '0002_auto_20200520_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='head_of_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='head', to='student.Student'),
        ),
    ]
