# Generated by Django 3.0.5 on 2020-05-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_remove_group_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course_id',
            new_name='course',
        ),
    ]
