# Generated by Django 3.0.5 on 2020-06-08 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_remove_group_head_of_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='floor',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
