# Generated by Django 3.0.5 on 2020-05-20 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_auto_20200520_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='number',
            new_name='floor',
        ),
    ]
