# Generated by Django 3.0.5 on 2020-05-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_auto_20200520_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='course',
            new_name='course_a',
        ),
    ]
