# Generated by Django 3.0.5 on 2020-05-10 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_student_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birthdate',
            new_name='birth_date',
        ),
    ]
