# Generated by Django 3.0.5 on 2020-05-11 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20200510_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='birth_date',
            new_name='birthdate',
        ),
    ]
