# Generated by Django 3.0.5 on 2020-05-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_auto_20200520_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='info',
        ),
        migrations.AddField(
            model_name='student',
            name='info',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo'),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
