# Generated by Django 3.0.5 on 2020-05-20 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20200520_1227'),
    ]

    operations = [
    ]
